# Generated by Django 2.0.2 on 2018-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rially', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name_plural': 'Penalties'},
        ),
    ]
