# Generated by Django 2.0.2 on 2018-02-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rially', '0003_auto_20180212_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsolve',
            name='content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtasksolve',
            name='content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picturesolve',
            name='content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasksolve',
            name='content',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
