# Generated by Django 2.0.2 on 2018-11-12 20:07

from django.db import migrations, models

def settings_forward(apps, schema_editor):
    SiteState = apps.get_model("rially", "SiteState")
    db_alias = schema_editor.connection.alias
    SiteState.objects.using(db_alias).create(submission_open=False)

def settings_reverse(apps, schema_editor):
    SiteState = apps.get_model("rially", "SiteState")
    db_alias = schema_editor.connection.alias
    SiteState.objects.using(db_alias).filter(submission_open=False).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('rially', '0007_sitestate'),
    ]

    operations = [
        migrations.RunPython(settings_forward, settings_reverse),
    ]
