from django.contrib import admin
from rially.models import *

admin.site.register(Aftermovie)
admin.site.register(TeamTelegramSession)
admin.site.register(Submitted)
admin.site.register(Team)
admin.site.register(Location)
admin.site.register(Puzzle)
admin.site.register(Task)
admin.site.register(Picture)
admin.site.register(PictureSolve)
admin.site.register(TaskSolve)
admin.site.register(LocationTask)
admin.site.register(LocationTaskSolve)
admin.site.register(LocationSolve)
admin.site.register(Bonus)
admin.site.register(Penalty)
admin.site.register(SiteState)
admin.site.register(QueueItem)
admin.site.register(PriorityQueueItem)
